journal/urls.py
from django.conf import settings
from django.conf.urls import include, url
from journal import views

urlpatterns = [
    url(r'^$', views.view_resources, name='resources'),
    url(r'^search/(?P<search_term>[\w ]+)$', views.view_resources, name='resources'),
    url(r'^languages/$', views.LanguageListView.as_view(), name='languages'),
    url(r'^frameworks/$', views.FrameworkListView.as_view(), name='frameworks'),
    url(r'^databases/$', views.DatabaseListView.as_view(), name='databases'),
    url(r'^libraries/$', views.LibraryListView.as_view(), name='libraries'),
    url(r'^technologies/$', views.TechnologyListView.as_view(), name='technologies'),
    url(r'^frontends/$', views.FrontEndListView.as_view(), name='frontends'),
    url(r'^resource/new$', views.create_resource, name='create_resource'),
    url(r'^language/$', views.LanguageView.as_view(), name='language'),
    url(r'^language/(?P<id>[0-9]+)$', views.LanguageView.as_view(), name='language'),
    url(r'^framework/$', views.FrameworkView.as_view(), name='framework'),
    url(r'^framework/(?P<id>[0-9]+)$', views.FrameworkView.as_view(), name='framework'),
    url(r'^database/$', views.DatabaseView.as_view(), name='database'),
    url(r'^database/(?P<id>[0-9]+)$', views.DatabaseView.as_view(), name='database'),
    url(r'^library/$', views.LibraryView.as_view(), name='library'),
    url(r'^library/(?P<id>[0-9]+)$', views.LibraryView.as_view(), name='library'),
    url(r'^technology/$', views.TechnologyView.as_view(), name='technology'),
    url(r'^technology/(?P<id>[0-9]+)$', views.TechnologyView.as_view(), name='technology'),
    url(r'^frontend/$', views.FrontEndView.as_view(), name='frontend'),
    url(r'^frontend/(?P<id>[0-9]+)$', views.FrontEndView.as_view(), name='frontend'),
    url(r'^resource/(?P<id>[0-9]+)', views.edit_resource, name='edit_resource'),
]

learnjournal/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('journal.urls', namespace='journal')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

journal/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class Resource(models.Model):

    name = models.CharField(max_length=256, blank=False, null=False)
    link = models.URLField(blank=True, null=True)
    language = models.ForeignKey('Language', blank=True, null=True)
    framework = models.ForeignKey('Framework', blank=True, null=True)
    frontend = models.ForeignKey('FrontEnd', blank=True, null=True)
    database = models.ForeignKey('Database', blank=True, null=True)
    library = models.ForeignKey('Library', blank=True, null=True)
    technology = models.ForeignKey('Technology', blank=True, null=True)
    attachment = models.FileField(default=None, blank=True, null=True)


class Language(models.Model):

    name = models.CharField(max_length=128, blank=False, null=False)

    def __str__(self):
        return self.name


class Framework(models.Model):

    name = models.CharField(max_length=128, blank=False, null=False)

    def __str__(self):
        return self.name


class Database(models.Model):

    name = models.CharField(max_length=128, blank=False, null=False)
    def __str__(self):
        return self.name


class Library(models.Model):

    name = models.CharField(max_length=128, blank=False, null=False)
    def __str__(self):
        return self.name


class Technology(models.Model):

    name = models.CharField(max_length=128, blank=False, null=False)
    def __str__(self):
        return self.name


class FrontEnd(models.Model):

    name = models.CharField(max_length=128, blank=True, null=False)

    def __str__(self):
        return self.name

journal/forms.py
from django.forms import ModelForm
from .models import Resource, Language, Framework, Database, Library, Technology, FrontEnd


class ResourceForm(ModelForm):
    class Meta:
        model = Resource
        fields = ['name', 'link', 'attachment', 'language', 'framework', 'frontend', 'database', 'library', 'technology' ]


class LanguageForm(ModelForm):
    class Meta:
        model = Language
        fields = ['name']


class FrameworkForm(ModelForm):
    class Meta:
        model = Framework
        fields = ['name']


class DatabaseForm(ModelForm):
    class Meta:
        model = Database
        fields = ['name']


class LibraryForm(ModelForm):
    class Meta:
        model = Library
        fields = ['name']


class TechnologyForm(ModelForm):
    class Meta:
        model = Technology
        fields = ['name']


class FrontEndForm(ModelForm):
    class Meta:
        model = FrontEnd
        fields = ['name']

journal/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.views import View
from .models import Resource, Language, Framework, Database, Library, Technology, FrontEnd
from .forms import ResourceForm, LanguageForm, FrameworkForm, DatabaseForm, LibraryForm, TechnologyForm, FrontEndForm
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse
from django.db.models import Q


def view_resources(request, search_term=None):
    resources = Resource.objects.all()
    if request.method == 'POST':
        search_term = request.POST.get('search_term', None)
    if search_term:
        resources = resources.filter(Q(name__icontains=search_term) | Q(link__icontains=search_term) | Q(language__name__icontains=search_term) | Q(framework__name__icontains=search_term) | Q(frontend__name__icontains=search_term) | Q(database__name__icontains=search_term) | Q(library__name__icontains=search_term) | Q(technology__name__icontains=search_term))

    return render(request, 'resources.html', {
        'resources': resources,
        'search_term': search_term,
    })


def create_resource(request):
    if request.method == 'POST':
        resource_form = ResourceForm(request.POST, request.FILES)
        if resource_form.is_valid():
            resource_form.save()
            return redirect(reverse('journal:resources'))
    else:
        resource_form = ResourceForm()
        return render(request, 'new_resource.html', {'resource_form': resource_form, 'adding': True})


def edit_resource(request, id):
    resource = get_object_or_404(Resource, id=id)
    if request.method == 'POST':
        resource_form = ResourceForm(request.POST, request.FILES, instance=resource)
        if resource_form.is_valid():
            resource_form.save()
            return redirect('journal:resources')
    else:
        resource_form = ResourceForm(instance=resource)
    return render(request, 'new_resource.html', {
        'id': resource.id,
        'resource_form': resource_form,
        'adding': False,
    })


class ItemsView(View):
    model = Resource
    template = 'list.html'
    iterable_name = 'items'
    view_link = None

    def get(self, request):
        items = self.model.objects.all()
        return render(request, self.template, {
            'view_link': self.view_link,
            self.iterable_name: items,
        })


class BaseView(View):

    form = None
    template = 'base_form.html'
    return_url = None
    model = Resource
    item_name = "resource"

    def get(self, request, *args, **kwargs):
        obj_id = kwargs.get('id', None)
        if obj_id:
            inst = get_object_or_404(self.model, id=obj_id)
            form = self.form(instance=inst)
            adding=False
        else:
            form = self.form()
            adding=True
        return render(request, self.template, {
            'id': obj_id,
            'form': form,
            'item_name': self.item_name,
            'adding': adding,
        })

    def post(self, request, *args, **kwargs):
        obj_id = kwargs.get('id', None)
        if obj_id:
            inst = get_object_or_404(self.model, id=obj_id)
            form = self.form(request.POST, instance=inst)
        else:
            form = self.form(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse(self.return_url))


class LanguageView(BaseView):
    form = LanguageForm
    model = Language
    return_url = "journal:languages"
    item_name = "language"


class LanguageListView(ItemsView):

    model = Language
    view_link = "journal:language"


class FrameworkView(BaseView):
    form = FrameworkForm
    model = Framework
    return_url = 'journal:frameworks'
    item_name = "framework"

class FrameworkListView(ItemsView):

    model = Framework
    view_link = "journal:framework"


class DatabaseView(BaseView):
    form = DatabaseForm
    model = Database
    return_url = 'journal:databases'
    item_name = "database"

class DatabaseListView(ItemsView):

    model = Database
    view_link = "journal:database"


class LibraryView(BaseView):
    form = LibraryForm
    model = Library
    return_url = 'journal:libraries'
    item_name = "library"

class LibraryListView(ItemsView):

    model = Library
    view_link = "journal:library"


class TechnologyView(BaseView):
    form = TechnologyForm
    model = Technology
    return_url = 'journal:technologies'
    item_name = "technology"


class TechnologyListView(ItemsView):

    model = Technology
    view_link = "journal:technology"


class FrontEndView(BaseView):
    form = FrontEndForm
    model = FrontEnd
    return_url = 'journal:frontends'
    item_name = "framework"


class FrontEndListView(ItemsView):

    model = FrontEnd
    view_link = "journal:frontend"

journal/templates/base.html
<html>
{% load staticfiles %}
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" href = "/static/main.css" />
	  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>{% block header_scripts %}
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">

    {% endblock %}
<title>{{ title }}</title>
</head>

<body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
		  <div class="container-fluid">
			<div class="navbar-header">
			  <a class="navbar-brand" href="{% url 'journal:resources' %}">
				Max's Programming Journal
			  </a>
			</div>
			<ul class="nav navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'journal:create_resource' %}">Create New Resource</a></li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'journal:resources' %}">View Resources</a>
                </li>
                <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Tech Types
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'journal:languages' %}">Languages</a>
                  <a class="dropdown-item" href="{% url 'journal:frameworks' %}">Frameworks</a>
                  <a class="dropdown-item" href="{% url 'journal:frontends' %}">Front End Frameworks</a>
                  <a class="dropdown-item" href="{% url 'journal:databases' %}">Databases</a>
                  <a class="dropdown-item" href="{% url 'journal:libraries' %}">Libraries</a>
                  <a class="dropdown-item" href="{% url 'journal:technologies' %}">Other</a>
                </div>
                </li>
			</ul>
            <form class="form-inline my-2 my-lg-0" action="{% url 'journal:resources' %}" method = "POST">
            {% csrf_token %}
            <input id="search_term" name="search_term" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
            </form>

		  </div>



      </nav>
	<div class="col-xs-12">
{% block content %}{% endblock %}
</body>
</html>

journal/templates/base_form.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block content %}
    <form method="post" class="form" action="{{return_url}}">
      {% csrf_token %}
      {{ form|bootstrap }}
      <input type="submit" class="btn btn-primary" value="{% if adding %}Create new{% else %}Save{% endif %} {{ item_name }}" />
    </form>
{% endblock%}

journal/templates/list.html
{% extends 'base.html' %}
{% block content %}
<table class="table">
    <tr><th>Name</th></tr>
    {% for item in items %}
    <tr><td><a href = "{% url view_link id=item.id %}">{{ item.name }}</a></td></tr>
    {% endfor %}
    <tr><td><a href = "{% url view_link %}">Create new</a></td></tr>
</table>
{% endblock %}

journal/templates/new_resource.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block content %}
    <form method="post" enctype="multipart/form-data" class="form">
      {% csrf_token %}
      {{ resource_form|bootstrap }}
      <input type="submit" class="btn btn-primary" value="{% if adding %}Create new{% else %}Save{% endif %} resource" />
    </form>
{% endblock%}

journal/templates/resources.html
{% extends 'base.html' %}
{% block content %}
{% if search_term %}
<h5> Resources containing search term "{{ search_term }}" - <a href="{% url 'journal:resources' %}" method = "GET">clear search</a></h5>
{% endif %}
<table class="table">
    <tr><th>Name</th><th>Link</th><th></th></tr>
    {% for res in resources %}
    <tr><td><a href = "{% url 'journal:edit_resource' id=res.id %}">{{ res.name }}</a> {% if res.attachment %}<span class="glyphicon glyphicon-paperclip"/>{% endif %}</td><td><a href="{{ res.link }}">{{ res.link}}</a></td><td>{% include 'partials/badges.html' with resource=res %}</td></tr>
    {% endfor %}
    <tr><td colspan="3"><a href = "{% url 'journal:create_resource' %}">Create new resource</a></td></tr>
</table>
{% endblock %}